name: code_learn
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  beamer: ^1.2.0
  google_fonts: ^2.2.0

  firebase_auth: ^3.3.5
  firebase_core: ^1.11.0
  firebase: ^9.0.2
  firebase_database: ^9.0.5
  objectid: ^2.0.0
  intl: ^0.17.0
  get_it: ^7.2.0
  stacked: ^2.2.8
  provider: ^6.0.2
  logger: ^1.1.0

  code_editor: ^1.3.1
  date_count_down: ^2.1.0
  responsive_builder: ^0.4.2
  cupertino_icons: ^1.0.4
  flutter_highlight: ^0.7.0
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/png/
